/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GgaUserCard {
        "includeFollowers": boolean;
        "includeFollowing": boolean;
        "includeGists": boolean;
        "includeRepos": boolean;
        "includeTwitter": boolean;
        "showStats": boolean;
        "user": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLGgaUserCardElement extends Components.GgaUserCard, HTMLStencilElement {
    }
    var HTMLGgaUserCardElement: {
        prototype: HTMLGgaUserCardElement;
        new (): HTMLGgaUserCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "gga-user-card": HTMLGgaUserCardElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface GgaUserCard {
        "includeFollowers"?: boolean;
        "includeFollowing"?: boolean;
        "includeGists"?: boolean;
        "includeRepos"?: boolean;
        "includeTwitter"?: boolean;
        "showStats"?: boolean;
        "user"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "gga-user-card": GgaUserCard;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gga-user-card": LocalJSX.GgaUserCard & JSXBase.HTMLAttributes<HTMLGgaUserCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
